answer_format: For each question present the reasoning followed by the correct answer
  within <final_answer> </final_answer> tags.
base_instruction: Pick A or B based on which has the stronger causal connection to
  the provided context. Ensure your answer is formatted as <final_answer>A</final_answer>
  or <final_answer>B</final_answer>.
few_shot_count: 5
generate_expert_identity: true
generate_intent_keywords: false
generate_reasoning: true
max_eval_batches: 6
min_correct_count: 3
mutate_refine_iterations: 3
mutation_rounds: 3
num_train_examples: 20
prompt_technique_name: critique_n_refine
questions_batch_size: 1
refine_instruction: true
refine_task_eg_iterations: 3
seen_set_size: 25
style_variation: 5
task_description: The dataset consists of premises and two possible choices for the
  effect or cause of the premise. The task is to determine which of the two choices
  (A or B) is the correct effect of the premise. The class will be extracted between
  the markers <final_answer>answer</final_answer>.
top_n: 1
unique_model_id: <unused_param>
